### ISSUE TITLE
关于在BOOKS目录中自行添加自抓网站.py

### ISSUE THREAD

**Issue by kkkpc** [ynhacler/RedKindle#5]
关于“RSS存在feeds表中，普通源地址直接填在url里，单独写的针对某一网站的抓取，填模块名”

这句话不是很明白。

我自己按照webpagebook基础类写了个 AAA.PY文件放在books目录

ubuntu重启此py程序刷新，并没有在主网页的订阅中看到此新加的AAA网站啊
单独写的针对某一网站的抓取，填模块名  这个指的是填在哪里啊?

Mysql下用命令看了feed表，发现只有默认的两条订阅网站，并没有把Books下的所有py模块loading进数据表中。  难道和cdhigh基于gae的kndleear不一样？

**Comment by ynhacler** [comment]
zai shu ju ku li zi ji cha ru :
AAA.py
jiu tian xie :AAA

在 2016-03-09 02:24:55，"kkkpc" notifications@github.com 写道：

关于“RSS存在feeds表中，普通源地址直接填在url里，单独写的针对某一网站的抓取，填模块名”

这句话不是很明白。

我自己按照webpagebook基础类写了个 AAA.PY文件放在books目录

ubuntu重启此py程序刷新，并没有在主网页的订阅中看到此新加的AAA网站啊
单独写的针对某一网站的抓取，填模块名 这个指的是填在哪里啊?

Mysql下用命令看了feed表，发现只有默认的两条订阅网站，并没有把Books下的所有py模块loading进数据表中。 难道和cdhigh基于gae的kndleear不一样？

**Comment by kkkpc** [comment]
已经OK了 谢谢。就是比起cdhigh的那套gae缺个投递日志，不太方便观察抓取以及投递报错。这个有什么方法吗。趁大神还在 赶紧问问 一会估计就睡了 哈哈

**Comment by kkkpc** [comment]
没事了，漏看了你有写到RQ-DASHBOARD
自己百度到了方法http://www.2cto.com/kf/201508/436479.html
就是gae那套带日志，自己懒了点  - -！

**Comment by ynhacler** [comment]
写的时候缺乏开发技巧没注意啊，所以log都忽略了。一直想维护升级下，太忙未遂

在 2016-03-09 23:01:31，"kkkpc" notifications@github.com 写道：

已经OK了 谢谢。就是比起cdhigh的那套gae缺个投递日志，不太方便观察抓取以及投递报错。这个有什么方法吗。趁大神还在 赶紧问问 一会估计就睡了 哈哈
